[theme]
base = 'light'
primaryColor = '#2B6CB0'        # professional blue
backgroundColor = '#FFFFFF'
secondaryBackgroundColor = '#F7FAFC'
textColor = '#1A202C'
font = 'sans serif'

[client]
showErrorDetails = false

[server]
headless = true
